### ISSUE TITLE
Menu RANGE (Android V1.21)

### ISSUE THREAD

**Issue by STEN-ZOE-FAN** [fesch/CanZE#416]
Remaining range by car is correctly shown, but the following fields
(Remaining Range by CanZE) are displaying mystery values.

**Comment by yoh-there** [comment]
Tap that line and enter your distance to destination. Please indicate if this issue can be closed.

**Comment by yoh-there** [comment]
I have misunderstood you I now realize. @fesch, this is about Technical -> Range. I am assigning this to you. @STEN-ZOE-FAN has a point ;-)

**Comment by fesch** [comment]
I know. This screen is not yet finished. I did not have the time yet, but I will finished it soon ;)

**Comment by FredLeudon** [comment]
![img_0466](https://cloud.githubusercontent.com/assets/12695496/22743315/1be0c958-ee1a-11e6-86d2-42b1d6b3da10.PNG)

Strange, when battery soc approch 0, max consumpsion change to 0.5kWh/100 km

**Comment by yoh-there** [comment]
Interesting observation. Maybe that is that tiny bit extra you get into what I call the "foot-room" (as opposed to "head-room"), so into the non-usable part of the battery, to get to a nearby charger in low performance mode? Pure speculation I know :-) Still, half a kWh on low speed should give you at least 8km.........

**Comment by solmoller** [comment]
Interesting. Did the car actually report limited mode?


Den 08/02/2017 17.01 skrev "yoh-there" <notifications@github.com>:

Interesting observation. Maybe that is that tiny bit extra you get into
what I call the "foot-room" (as opposed to "head-room"), so into the
non-usable part of the battery, to get to a nearby charger in low
performance mode? Pure speculation I know :-) Still, half a kWh on low
speed should give you at least 8km.........

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fesch/CanZE/issues/416#issuecomment-278370266>, or mute
the thread

**Comment by FredLeudon** [comment]
Yes, limited mode.

Arriving with 0 kWh in batt ;-)

I forgot to take a picture at arrival.

Frédéric RICHARD

**Comment by solmoller** [comment]
Ok.  My experience is that SOH suffers from that treatment

BR
Henrik

Den 09/02/2017 7.22 AM skrev "FredLeudon" <notifications@github.com>:

> Yes, limited mode.
>
> Arriving with 0 kWh in batt ;-)
>
> I forgot to take a picture at arrival.
>
> Frédéric RICHARD
>
> > Le 9 févr. 2017 à 07:04, Henrik Møller Jørgensen <

**Comment by zmeglic** [comment]
What would this remaining range by CanZE supposed to be displaying? These large numbers make no sense.
![screenshot_20170213-113141](https://cloud.githubusercontent.com/assets/16178106/22920099/9f8266ae-f293-11e6-97bf-745b78ae1c03.png)

**Comment by fesch** [comment]
I will delete the entire screen.
Too many question about a screen that is technical and not yet finished.
Sorry.
