### ISSUE TITLE
Zoe Voice

### ISSUE THREAD

**Issue by erlazz** [fesch/CanZE#483]
As you know Zoe already have a "voice" to alert pedestrians and bike users but for my experience is often not audible or understood. So I placed a bluetooth speaker on Zoe 12V service battery to speak a music clip from my smartphone when driving on some people-busy roads. https://www.ebay.com/p/Bolse-12w-Portable-Smart-NFC-Wireless-Bluetooth-V4-0-Speaker-Two-Large-40mm-6w/1042253385   This seems to my friends more like a loud car audio then a vehicle alert, and do not switch off until I close music player on smartphone.  I read that "Acoustic Vehicle Alerting Systems" will be mandatory in 2019 on EVs, and will be volume and frequency incremental with speed, stopping after the 30km/h Is it maybe possible for you to implementet a feature like that in CanZe sw?

**Comment by yoh-there** [comment]
Haha, fun. To be honest, but this is my personal opinion, I have actually killed the VPS by pulling it's fuse. I hate the thing to bits: why make noise because old tech cars do? It's like the times when a guy with a bell needed to walk in front of an "auto mobile", because it didn't make the horse feet noises. So I won't make it for sure ;-) And what if somebody calls the phone :D :D But maybe somebody else wants to do it.

**Comment by FrancescZOE** [comment]
REnault should alow a lower acoustic claxon, like other GM do in volt and BOLT. To push claxon  near a peaton is too noisy and disgusting.

**Comment by yoh-there** [comment]
https://www.youtube.com/watch?v=lv8wqnk_TsA :-)
