### ISSUE TITLE
Why does CanZE think a granny is a rapid?

### ISSUE THREAD

**Issue by KotekBesar** [fesch/CanZE#502]
Well, I’ve never known this before...

As my granny cable died recently I bought a new one. Just testing it now and CanZE is seeing it as:
Phases: 3
Available Charging Power kW: 51.0

**Comment by yoh-there** [comment]
Will have a look at that. 51 is probably "unavailable", but not showing that is pretty lazy. Thanks

**Comment by yoh-there** [comment]
![image](https://user-images.githubusercontent.com/4979670/44004797-fe00b550-9e68-11e8-8ae8-a2ffc1bf78eb.png)

**Comment by yoh-there** [comment]
Just some technical info for reference.
Phases is set to 3 if the Available charging power (i.e. 11 for 11 kW) is greater than a quarter of the pilot max amp signal (for an 11 kW charger this is 16 amps, so 4).

Since the reported Availabe Charging Power is 51, and the pilot 9 amps, Canze concludes 3 phases. The problem is not the Phases, it's the Available Charging Power (ACP).

Remember that the only thing the charger is sending out is the pilot max amp. 9 amps seems to be a completely reasonable value, so I would say that it is not the charger.

ACP is field 427.40 and is sent out by the EVC. The documentation says it's "unavailable" value is 76.5, which is nowhere near the reported 51.

@KotekBesar  this is the Q210 (black one) right? (I am asking because I own that model myself and should be able to tweak the granny charger down to 9A to try to recreate). Also, can you please provide the firmware versions of the LBC, the EVC and if possible the BCB?

Hypothesis: with the latest software upgrade, maybe they slightly redefined the  meaning of the field.

**Comment by KotekBesar** [comment]
Good evening!

Very interesting, thank you. 

You’re right, it’s the black 2015 Zoe Intens Q210.

LBC: DiagVersion: 25. Supplier: AE0. Soft: 0854. Version: 0000.
EVC: 0A70
BCB: 0870

Hope those numbers are correct. They’re from the “version” section of the output.

**Comment by yoh-there** [comment]
I checked my own Q210. When there is no charger at all connected, the ACP is 51.0 too. This seems to indicate a "not available" status, though this is not in line with the documentation we have (should be 76.5).

First I assumed frame 427 was simply not received, but this hypothesis does not hold: available energy is taken from the same frame and seems in line with the SOC.

I can only conclude that:
- 51.0 is to be interpreted as "unavailable" (and I can modify Canze to display that);
- the car is unable - unwilling to make the calculation based on 9 A pilot signal on single phase (there is nothing I can do about that)

I can check with my granny charger, if needed fiddle until pilot amps shown in CanZE is 9 A. However, if I see either the same result, or a reasonable ACP, there is still nothing I can do about it.

Course of action suggested is:
- interpret all ACP > 43 kW as "unavailable"
- if so, do not state a phase count

**Comment by KotekBesar** [comment]
Excellent work! 👍

**Comment by yoh-there** [comment]
Fixed as described in 10677ac
