### ISSUE TITLE
Power economy per trip

### ISSUE THREAD

**Issue by LakesGeek** [fesch/CanZE#513]
As I don't reset the B trip on my Zoe often (I find the range meter adjusts itself quite accurately over time) I'd love to be able to see what my mpkwh is on a single trip through CanZE, if it could be given as a raw average in the app since it was last reset, and a reset button provided.

This ties in somewhat with my other suggestion  for a mpkwh readout but obviously would make sense to work for the existing kwh/100m option as well.

**Comment by yoh-there** [comment]
Would you accept a kwh/mi? Just kidding. My thought would be to implement this in the driving screen the exact same way it does "range at distance". I just think that (for both) we should save the starting values non-volatile, so a crash or clear from memory would not reset it all. @fesch use the preferences store for things like this? What is your guidance?

BTW this implies NOT going with your "since it was last reset" suggestion, just the reset by tapping on the number and probably an "Are you sure".

**Comment by yoh-there** [comment]
I have investigated this a bit further. In the current fields we use, there is not a cumulative energy used field, though I am sure it is hidden somewhere in the thousands of fields in the car's system. Maybe it is this one
7ec,24,47,.001,0,0,kwh,2233DC,6233DC,ff,This variable allows to memorize the energy consumed
but I need to experiment with that. If I cannot find a suitable field, this is not possible to implement with reasonable precision.

**Comment by yoh-there** [comment]
Never mind, that variable won't work (returns a NaN). However we can use 7ec.2233dd.24, which is the current trip B energy. Trip B distance is 7ec.2233de.24.

We  should memorize these and the odo in the preference file as the CanZE trip is started.

To deal with trip computer resets, if (current odo - current trip) > (memorized odo - memorized trip), with a one km leeway,  there was a trip reset and CanZE should display "Car's trip B was reset Press here to (re)restart" instead of the actual trip consumption

Both this test as well as the trip consumption should be calculated once per 10 seconds is my thinking.

**Comment by yoh-there** [comment]
Closed #2deb082
