### ISSUE TITLE
Clipping bug in the graphs?

### ISSUE THREAD

**Issue by yoh-there** [fesch/CanZE#530]
I am not 100% sure where the issue is. Looks like on the widgets nothing is drawn when either the value is above the scale or exactly on the top (maybe also bottom) scale. Here are a few examples. It is most noticeable at the gradients, but it might be a common graphing problem.

![image](https://user-images.githubusercontent.com/4979670/52901575-9fe01980-3205-11e9-85b9-3bc22a03c492.png)
(middle graph)

![image](https://user-images.githubusercontent.com/4979670/52901587-c56d2300-3205-11e9-8e6b-e524ed8353cd.png)
(bottom graph)

Let me know if there is something I can do please.

**Comment by fesch** [comment]
I got this now twice too. First thought about a problem of the new value limiting code I've added, but ended it in rejecting this idea, because missing values, which we know from other cases, result in big triangles so a simple empty space should not be there.

So finally this seams to be a drawing problem and I need to investigate into that direction.

A workaround, increasing the scale and does avoiding getting value right on the limits of the graph will probably do the trick as well ;)

**Comment by yoh-there** [comment]
Scaling would work for the delta, but not for the power. I will try to recreate this using the http dongle emulator with stable, fixed values and will let you know.

Speaking about triangles: I still see them occasionally. Do you think it is caused by Nan's?

**Comment by yoh-there** [comment]
I think I found it. A regression of trying to get rid of the triangles, combined with faulty boolean logic. I will test and push if fixed.

**Comment by yoh-there** [comment]
Tested. #a92e956 Closing
