### ISSUE TITLE
CanzeDataSource instance null

### ISSUE THREAD

**Issue by yoh-there** [fesch/CanZE#553]
I have to give up on this one, sorry....

Found in the crash log. getInstance is called in MainActivity.onCreate with getBaseContext(), so I don't see a mechanism where the property instance can be null causing this Throw.

java.lang.Error: 
  at lu.fisch.canze.database.CanzeDataSource.getInstance (CanzeDataSource.java:49)
  at lu.fisch.canze.activities.SettingsActivity$7.onClick (SettingsActivity.java:466)

If we can't pinpoint this, I suggest a mechanism where it doesn't crash, but then again, the context of the error is Android 6 on S10, which looks weird to me. So, we should consider a "dontfix"

**Comment by fesch** [comment]
I suppose this is due to the following, which is line #49:

`if (instance == null) throw new Error("Must call at least once with given context!");`

So there must be some place where the getInstance Method is being called before the context has been set. If we change this and return "null" instead, the above situation should produce a NullPointerException and we could find out where exactly the call is being made ...

**Comment by yoh-there** [comment]
Done that change. Closing this issue, will reopen if this crash comes up again. TBH I have never seen it before, so it is rare.

**Comment by yoh-there** [comment]
BTW, as I suspect this happening because of the threaded hourly cleanup, I have added an extra check there. Commit #203f9016
