### ISSUE TITLE
29 kWh Zoe Q210 battery?

### ISSUE THREAD

**Issue by alcio313** [fesch/CanZE#562]
![Screenshot_20190518-125524](https://user-images.githubusercontent.com/7809097/57968624-4f479c00-796d-11e9-9475-d2f662f11ea3.png)
![IMG_20190518_130136](https://user-images.githubusercontent.com/7809097/57968627-52db2300-796d-11e9-9e06-99b9875dc5ec.jpg)
Is that an app's bug?

**Comment by yoh-there** [comment]
Available energy comes straight from the car, there is not a single calculation involved.

Energy to full is a calculated value. It takes the user state of charge percentage fro the car, then applies the formula: Energy to full = (100% - SOC%) / SOC% * available energy.

In your case the SOC was 82% so it assumed the energy to full was 18/82 * 24.4.

It seems to me the issue is the Energy to full as at 82% you would expect roughly 18 kWh. I double checked on my car (also a Q210) and the figures were quite normal. I have no suggestions other than checking the firmware of the EVC. I can dig up mine later today.

ps: 165 km range for 82% seems quite high too unless you are a hypermiller. So I suspect one of the car's computers lost it's mind. Maybe ask the dealer to reset?
