### ISSUE TITLE
“Use ISOTP fields” is forced ON

### ISSUE THREAD

**Issue by Jemandaa** [fesch/CanZE#760]
Hello, I have problems with DTC Readouts on Android 8 + simple VLink BT Adapter in a Zoe R90 PH1
So i tried to turn of ISOPT fields but it won’t let me. Even tried to reinstall the App because i thought it would be turned off by default, but it isn’t. Any help would be greatly appreciated & Thanks for this Gem of an App

**Comment by yoh-there** [comment]
The setting is dependent on the car type. A Ph2 car (plug in the foot well) does not work with the non-ISOTP setting as it's internal gateway blocks that. It is useless to try to change it.

The Ph1 model (plug in the coin tray) can use both, but we have programmed a slight preference for non-ISOTP, mostly because it is much faster when using the CanSee dongle. This setting you can override, though it will revert when changing car type. Hope this helps.
